spring:
  kafka:
    ## admin:
    ##  properties:
    ##     sasl.kerberos.service.name: kafka
    ##   security:
    ## protocol: SASL_SSL
    bootstrap-servers:
      localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: kafka-stream-employee-example
      client-id: kafka-stream-employee-example
      key: kafka-stream-employee-example
      topics:
        consumers: sanmx.seb.platforms.back.payments.plard.cards.business.basic.current-account
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: kafka-stream-employee-example
      client-id: kafka-stream-employee-example
      key: kafka-stream-employee-example
      topics:
        producers: sanmx.seb.platforms.back.payments.plard.cards.business.basic.current-account
      properties:
        max.partition.fetch.bytes: 2097152
        sasl.kerberos.service.name: kafka
        enable:
          idempotence: false
    listener:
      concurrency: 6
      type: BATCH
      ack-mode: BATCH
      poll-timeout: 1


---
server:
  port: 8090